// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6DAK0oh1WgjhWm_L5DGkIAKCv6t5hYUs',
    appId: '1:409531517991:web:a17c719ed3491e6b8f1202',
    messagingSenderId: '409531517991',
    projectId: 'office-quote-game',
    authDomain: 'office-quote-game.firebaseapp.com',
    storageBucket: 'office-quote-game.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJAbq-klETXQ9bA7SoQGf0SKGsuVEIL7I',
    appId: '1:409531517991:android:1a926763d7b3753f8f1202',
    messagingSenderId: '409531517991',
    projectId: 'office-quote-game',
    storageBucket: 'office-quote-game.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMCpgeesyUlth5bLA4RYQgc4VSeDvba9E',
    appId: '1:409531517991:ios:fad5776cdf587fca8f1202',
    messagingSenderId: '409531517991',
    projectId: 'office-quote-game',
    storageBucket: 'office-quote-game.appspot.com',
    iosClientId: '409531517991-6p4b82f3f0dsv26tq02eauo54m0pn7b8.apps.googleusercontent.com',
    iosBundleId: 'com.officequotegame.app',
  );
}
